[server]
enableWebsocket = false
enableWebsocketCompression = false
headless = true
maxUploadSize = 200
fileWatcherType = "none"

[browser]
gatherUsageStats = false
serverAddress = ""
serverPort = 0

[global]
disableWatchdogWarning = true
